blank_issues_enabled: true
contact_links:
  - name: Issue with Quarto CLI
    url: https://github.com/quarto-dev/quarto-cli
    about: Please report issues with the Quarto CLI here
  - name: Quarto Community Support (Quarto 1)
    url: https://github.com/quarto-dev/quarto-cli/discussions/categories/q-a-q1
    about: Please ask and answer questions about Quarto 1 in our Discussion board
  - name: Quarto Community Support (Quarto 2)
    url: https://github.com/quarto-dev/quarto-cli/discussions/categories/q-a-q2
    about: Quarto 2 is experimental and not ready for production use. Please ask and answer questions about it in our Discussion board
