install:
  rm -rf *.vsix && vsce package && code --install-extension *.vsix && positron --install-extension *.vsix

install-vscode:
  rm -rf *.vsix && vsce package && code --install-extension *.vsix

install-positron:
  rm -rf *.vsix && vsce package && positron --install-extension *.vsix

# Build for dev and watch for changes.
# This delegates to the build script at the root to build dependencies if needed.
dev:
  cd ../.. && yarn run dev-vscode
