name: Test Positron API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-positron:
    runs-on: macos-latest
    name: Test Positron API
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Build vscode extension
        run: |
          yarn install
          yarn run build-vscode
      - name: Run Positron API tests
        uses: posit-dev/setup-positron@main
        with:
          positron-channel: stable
